config/routes.rb
Rails.application.routes.draw do
  get 'colleges/show'
  devise_for :students,controllers: { registrations: 'students/registrations' }
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :students, only: [:show,:edit,:update]
  resources :colleges, only: [:index,:new, :create,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
	has_many :students, dependent: :destroy
	has_one_attached :logo
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :college
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
        	devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:password,:batch,:gender,:college_id,:avatar])
        end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
	before_action :authenticate_student!
	def new
	end

	def index
		@colleges = College.all
	end

	def show
  		@college = College.find(params[:id])
        Rails.cache.write(params[:id],Rails.cache.fetch(params[:id]){0}+1)
        Rails.cache.write("current"+params[:id]+"_"+current_student[:email],current_student[:email],expires_in: 10.minute)
        @user_arr = []
        $redis.keys("current"+params[:id]+"*_*").each do |elem|
        	@user_arr.push(Rails.cache.read(elem))
        end
 	end

	def create
	  College.create(post_params)
	  redirect_to colleges_path
	end
	
	private
	def post_params
	  params.require(:college).permit(:name, :address, :current_views, :total_views,:logo)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_student!

  def index
  	redirect_to current_student
  end
end

app/controllers/students/confirmations_controller.rb
# frozen_string_literal: true

class Students::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/students/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Students::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/registrations_controller.rb
# frozen_string_literal: true

class Students::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @colleges = College.all
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:password,:batch,:gender,:college_id,:avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def show
	end

	def edit
		@student = Student.find(params[:id])
		@colleges = College.all
	end

	def update
		current_student.update(student_params)
		redirect_to current_student
	end

	def student_params
		params.require(:student).permit(:name,:batch,:gender,:avatar,:college_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/colleges/index.html.erb
<h2>Colleges List</h2>
<ul>
  <% @colleges.each do |college| %>
    <li>
      <%= college.id %>
      <%= college.name %>
      <%= college.address %>
      <%= link_to "view", college_path(:id => college.id) %>
    </li>
  <% end %>
</ul>

<span><%= link_to "Add new college", new_college_path %></a>

app/views/colleges/new.html.erb
<br>
<h2>Create college</h2>
<br>
<%= form_for College.new do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :address, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :logo, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.file_field :logo, class: 'form-control' %>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit 'Create College', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/colleges/show.html.erb
<% @college = College.find(params[:id]) %>
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @college.logo.attached? %>
          <%= image_tag @college.logo %>
        <%end %>
      </div>
    </div>
    
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @college.name %></h2>
      </div>
      <ul class="posts">
        <li><span>Address : </span> <%= @college.address %></li>
        <li><span>Total_visits : </span> <%= Rails.cache.read(params[:id]) %></li>
      </ul>
      <% if @user_arr.any? %>
        <span>Current users : </span>
        <ul>
          <% @user_arr.each do |each_user| %>
            <li><%= each_user %></li>
          <% end %>
        </ul>
      <% end %> 

      <span><%= link_to "All_colleges", colleges_path %></a>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pratilipi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="#">
            Assignment
          </a>
        </div>
        <div class="student-section">
          <% if student_signed_in? %>
            <a href="<%= colleges_path %>">
              Colleges
            </a>
            <a href="<%= student_path(current_student)%>">
              <i class="fa fa-user"></i>
            </a>
            <a href="<%= destroy_student_session_path%>" data-method="delete">
              <i class="fa fa-sign-out"></i>
            </a>
          <% else %>
            <a href="<%= new_student_session_path%>">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>

        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>Assignment by PRATILIPI</li>
        </ul>
      </nav>
    </footer>
  </body>
</html>

app/views/students/edit.html.erb
<div class="student-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <!-- Form edit profile -->

      <%= form_with model: current_student, local: true, html: {class: "form-horizontal form-edit-student"} do |f| %>
        <div class="form-group row">
          <div class="wrapper col-sm-3 col-form-label">
            <% if current_student.avatar.attached? %>
              <%= image_tag current_student.avatar %>
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%= current_student.name %></p>
            <a class="change-photo" href="">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :batch, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :batch, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :college_id, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.select :college_id, options_for_select(@colleges.collect{ |u| [u.name, u.id] }), class: 'form-control' %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>


    </div>
  </div>
</div>

app/views/students/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/students/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/students/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if current_student.avatar.attached? %>
          <%= image_tag current_student.avatar %>
        <%end %>
      </div>
    </div>
    
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= current_student.name %></h2>
        <a class="edit-profile" href="<%= edit_student_path(current_student) %>">
          <button>Edit Profile</button>
        </a>
      </div>
      <ul class="posts">
        <li><span>Batch : </span> <%= current_student.batch %></li>
        <li><span>Gender : </span> <%= current_student.gender %></li>
      </ul>
      <% if current_student.college_id %>
        <span>College : </span><%= link_to College.find(current_student.college_id).name , college_path(:id => current_student.college_id) %>
      <% end %>
    </div>
  </div>
</div>